spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:4432}/${DB_NAME:openws}
    username: ${DB_USER:warehouse_user}
    password: ${DB_PASSWORD:warehouse_password}
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: false

server:
  port: ${PORT:19090}

ozon:
  request-pause-ms: ${OZON_REQUEST_PAUSE_MS:1500}
  api-url: https://api-seller.ozon.ru/v3/posting/fbs/list
  fbo-list-url: https://api-seller.ozon.ru/v3/supply-order/list
  fbo-get-url: https://api-seller.ozon.ru/v3/supply-order/get
  fbo-bundle-url: https://api-seller.ozon.ru/v1/supply-order/bundle
  product-list-url: https://api-seller.ozon.ru/v3/product/list
  product-attributes-url: https://api-seller.ozon.ru/v4/product/info/attributes

google:
  service-account-key: ${GOOGLE_SERVICE_ACCOUNT_KEY:google-credentials.json}
